/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'paymentStatus' : IDL.Text,
  'transactionType' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'notes' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTransaction' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailySummary' : IDL.Func(
      [IDL.Text],
      [IDL.Nat, IDL.Nat, IDL.Int],
      ['query'],
    ),
  'getExpenseCategories' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getMonthlySummary' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Nat, IDL.Nat, IDL.Int],
      ['query'],
    ),
  'getMyTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getPendingTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateTransaction' : IDL.Func([Transaction], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'paymentStatus' : IDL.Text,
    'transactionType' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'notes' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTransaction' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailySummary' : IDL.Func(
        [IDL.Text],
        [IDL.Nat, IDL.Nat, IDL.Int],
        ['query'],
      ),
    'getExpenseCategories' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getMonthlySummary' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Nat, IDL.Nat, IDL.Int],
        ['query'],
      ),
    'getMyTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getPendingTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateTransaction' : IDL.Func([Transaction], [], []),
  });
};

export const init = ({ IDL }) => { return []; };